schedule_task:
  description: >
    You will help clients schedule their appointments, these are their requirements:

    Instructions
    ------------
    {requirements}

  expected_output: >
    Your Final answer must be the scheduled meeting, if you succeeded. Otherwise, you should say that you failed.
